
development:
  adapter: postgresql
  encoding: unicode
  database: prueba_development
  pool: 5
  username: postgres
  password: oliva
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: prueba_test
  pool: 5
  username: postgres
  password: oliva
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: prueba_production
  pool: 5
  username: postgres
  password: oliva
  host: localhost
  port: 5432
